site_name: CTO framework
site_url: https://ctoframework.com
repo_url: https://github.com/ctoframework/static-website
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides

  logo: images/ctoframework-logo.png
  favicon: images/ctoframework-logo.ico

  features:
    - navigation.tabs
    - navigation.path
    - navigation.footer
    - content.action.edit
    - content.code.copy

  palette: 
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - meta
  - tags
  - search
  - git-revision-date-localized:
      enable_creation_date: false

extra:
  alternate:
    - name: English
      link: /
      lang: en
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ctoframework
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ctoframework/
    - icon: fontawesome/brands/github
      link: https://github.com/ctoframework
  analytics:
    provider: google
    property: G-QSBG34WM6H

extra_css:
  - styles/extra.css
